-- =====================================================================
--  FilmBox — jeu de données du projet fil rouge (séance 1)
--  Films et castings réels ; membres, notes et visionnages fictifs.
--  Script ré-exécutable : il supprime puis recrée toutes les tables.
--  À charger dans une base dédiée :  CREATE DATABASE filmbox;
-- =====================================================================

-- (listes et liste_films sont créées pendant la mission M1)
DROP TABLE IF EXISTS liste_films, listes, journal, notes, casting, films, sagas, personnes, utilisateurs CASCADE;

CREATE TABLE sagas (
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom  VARCHAR(60) NOT NULL UNIQUE
);

CREATE TABLE films (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titre              VARCHAR(120) NOT NULL,
    annee              INTEGER      NOT NULL CHECK (annee BETWEEN 1888 AND 2100),
    genre              VARCHAR(30)  NOT NULL,
    saga_id            INTEGER REFERENCES sagas(id),
    film_precedent_id  INTEGER REFERENCES films(id)     -- épisode précédent dans la saga
);

CREATE TABLE personnes (
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom  VARCHAR(80) NOT NULL UNIQUE
);

CREATE TABLE casting (
    film_id     INTEGER NOT NULL REFERENCES films(id),
    personne_id INTEGER NOT NULL REFERENCES personnes(id),
    role        VARCHAR(12) NOT NULL CHECK (role IN ('acteur', 'realisateur')),
    PRIMARY KEY (film_id, personne_id, role)
);

CREATE TABLE utilisateurs (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pseudo      VARCHAR(30) NOT NULL UNIQUE,
    ville       VARCHAR(50),
    inscrit_le  DATE NOT NULL
);

CREATE TABLE notes (
    utilisateur_id INTEGER NOT NULL REFERENCES utilisateurs(id),
    film_id        INTEGER NOT NULL REFERENCES films(id),
    note           NUMERIC(2,1) NOT NULL CHECK (note BETWEEN 0.5 AND 5),
    note_le        DATE NOT NULL,
    PRIMARY KEY (utilisateur_id, film_id)                -- une note par membre et par film
);

CREATE TABLE journal (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    utilisateur_id  INTEGER NOT NULL REFERENCES utilisateurs(id),
    film_id         INTEGER NOT NULL REFERENCES films(id),
    date_visionnage DATE    NOT NULL
);

-- ---------- Sagas ----------
INSERT INTO sagas (nom) VALUES ('Retour vers le futur'), ('The Dark Knight'), ('X-Men : la prélogie');

-- ---------- Films ----------
INSERT INTO films (titre, annee, genre, saga_id) VALUES
 ('Apollo 13', 1995, 'Drame', NULL),                                  -- 1
 ('Mystic River', 2003, 'Thriller', NULL),                            -- 2
 ('Des hommes d''honneur', 1992, 'Drame', NULL),                      -- 3
 ('X-Men : Le Commencement', 2011, 'Science-fiction', 3),             -- 4
 ('X-Men : Days of Future Past', 2014, 'Science-fiction', 3),         -- 5
 ('X-Men : Apocalypse', 2016, 'Science-fiction', 3),                  -- 6
 ('Forrest Gump', 1994, 'Drame', NULL),                               -- 7
 ('Seul au monde', 2000, 'Aventure', NULL),                           -- 8
 ('Il faut sauver le soldat Ryan', 1998, 'Guerre', NULL),             -- 9
 ('Arrête-moi si tu peux', 2002, 'Policier', NULL),                   -- 10
 ('Titanic', 1997, 'Romance', NULL),                                  -- 11
 ('Inception', 2010, 'Science-fiction', NULL),                        -- 12
 ('Les Infiltrés', 2006, 'Policier', NULL),                           -- 13
 ('Once Upon a Time… in Hollywood', 2019, 'Comédie', NULL),           -- 14
 ('Le Loup de Wall Street', 2013, 'Comédie', NULL),                   -- 15
 ('Fight Club', 1999, 'Thriller', NULL),                              -- 16
 ('Ocean''s Eleven', 2001, 'Policier', NULL),                         -- 17
 ('Seven', 1995, 'Thriller', NULL),                                   -- 18
 ('Batman Begins', 2005, 'Action', 2),                                -- 19
 ('The Dark Knight', 2008, 'Action', 2),                              -- 20
 ('The Dark Knight Rises', 2012, 'Action', 2),                        -- 21
 ('Les Évadés', 1994, 'Drame', NULL),                                 -- 22
 ('Intouchables', 2011, 'Comédie', NULL),                             -- 23
 ('La Môme', 2007, 'Drame', NULL),                                    -- 24
 ('The Artist', 2011, 'Comédie', NULL),                               -- 25
 ('Le Fabuleux Destin d''Amélie Poulain', 2001, 'Comédie', NULL),     -- 26
 ('La Haine', 1995, 'Drame', NULL),                                   -- 27
 ('Retour vers le futur', 1985, 'Science-fiction', 1),                -- 28
 ('Retour vers le futur II', 1989, 'Science-fiction', 1),             -- 29
 ('Retour vers le futur III', 1990, 'Science-fiction', 1);            -- 30

-- Chaînage des sagas : chaque épisode pointe vers le précédent
UPDATE films SET film_precedent_id = 4  WHERE id = 5;
UPDATE films SET film_precedent_id = 5  WHERE id = 6;
UPDATE films SET film_precedent_id = 19 WHERE id = 20;
UPDATE films SET film_precedent_id = 20 WHERE id = 21;
UPDATE films SET film_precedent_id = 28 WHERE id = 29;
UPDATE films SET film_precedent_id = 29 WHERE id = 30;

-- ---------- Personnes et casting ----------
-- Table de travail temporaire : (film, personne, rôle) en toutes lettres
CREATE TEMP TABLE _casting (film_id INTEGER, nom VARCHAR(80), role VARCHAR(12));
INSERT INTO _casting VALUES
 (1,'Tom Hanks','acteur'),(1,'Kevin Bacon','acteur'),(1,'Bill Paxton','acteur'),(1,'Gary Sinise','acteur'),(1,'Ed Harris','acteur'),(1,'Ron Howard','realisateur'),
 (2,'Sean Penn','acteur'),(2,'Tim Robbins','acteur'),(2,'Kevin Bacon','acteur'),(2,'Laurence Fishburne','acteur'),(2,'Clint Eastwood','realisateur'),
 (3,'Tom Cruise','acteur'),(3,'Jack Nicholson','acteur'),(3,'Demi Moore','acteur'),(3,'Kevin Bacon','acteur'),(3,'Rob Reiner','realisateur'),
 (4,'James McAvoy','acteur'),(4,'Michael Fassbender','acteur'),(4,'Jennifer Lawrence','acteur'),(4,'Kevin Bacon','acteur'),(4,'Matthew Vaughn','realisateur'),
 (5,'Hugh Jackman','acteur'),(5,'James McAvoy','acteur'),(5,'Michael Fassbender','acteur'),(5,'Jennifer Lawrence','acteur'),(5,'Omar Sy','acteur'),(5,'Bryan Singer','realisateur'),
 (6,'James McAvoy','acteur'),(6,'Michael Fassbender','acteur'),(6,'Jennifer Lawrence','acteur'),(6,'Bryan Singer','realisateur'),
 (7,'Tom Hanks','acteur'),(7,'Robin Wright','acteur'),(7,'Gary Sinise','acteur'),(7,'Robert Zemeckis','realisateur'),
 (8,'Tom Hanks','acteur'),(8,'Helen Hunt','acteur'),(8,'Robert Zemeckis','realisateur'),
 (9,'Tom Hanks','acteur'),(9,'Matt Damon','acteur'),(9,'Tom Sizemore','acteur'),(9,'Vin Diesel','acteur'),(9,'Steven Spielberg','realisateur'),
 (10,'Leonardo DiCaprio','acteur'),(10,'Tom Hanks','acteur'),(10,'Steven Spielberg','realisateur'),
 (11,'Leonardo DiCaprio','acteur'),(11,'Kate Winslet','acteur'),(11,'James Cameron','realisateur'),
 (12,'Leonardo DiCaprio','acteur'),(12,'Joseph Gordon-Levitt','acteur'),(12,'Elliot Page','acteur'),(12,'Tom Hardy','acteur'),(12,'Marion Cotillard','acteur'),(12,'Michael Caine','acteur'),(12,'Christopher Nolan','realisateur'),
 (13,'Leonardo DiCaprio','acteur'),(13,'Matt Damon','acteur'),(13,'Jack Nicholson','acteur'),(13,'Martin Scorsese','realisateur'),
 (14,'Leonardo DiCaprio','acteur'),(14,'Brad Pitt','acteur'),(14,'Margot Robbie','acteur'),(14,'Quentin Tarantino','realisateur'),
 (15,'Leonardo DiCaprio','acteur'),(15,'Jonah Hill','acteur'),(15,'Margot Robbie','acteur'),(15,'Jean Dujardin','acteur'),(15,'Martin Scorsese','realisateur'),
 (16,'Brad Pitt','acteur'),(16,'Edward Norton','acteur'),(16,'Helena Bonham Carter','acteur'),(16,'David Fincher','realisateur'),
 (17,'George Clooney','acteur'),(17,'Brad Pitt','acteur'),(17,'Matt Damon','acteur'),(17,'Julia Roberts','acteur'),(17,'Steven Soderbergh','realisateur'),
 (18,'Brad Pitt','acteur'),(18,'Morgan Freeman','acteur'),(18,'David Fincher','realisateur'),
 (19,'Christian Bale','acteur'),(19,'Michael Caine','acteur'),(19,'Liam Neeson','acteur'),(19,'Morgan Freeman','acteur'),(19,'Gary Oldman','acteur'),(19,'Christopher Nolan','realisateur'),
 (20,'Christian Bale','acteur'),(20,'Heath Ledger','acteur'),(20,'Michael Caine','acteur'),(20,'Morgan Freeman','acteur'),(20,'Gary Oldman','acteur'),(20,'Christopher Nolan','realisateur'),
 (21,'Christian Bale','acteur'),(21,'Tom Hardy','acteur'),(21,'Anne Hathaway','acteur'),(21,'Joseph Gordon-Levitt','acteur'),(21,'Marion Cotillard','acteur'),(21,'Michael Caine','acteur'),(21,'Gary Oldman','acteur'),(21,'Morgan Freeman','acteur'),(21,'Christopher Nolan','realisateur'),
 (22,'Tim Robbins','acteur'),(22,'Morgan Freeman','acteur'),(22,'Frank Darabont','realisateur'),
 (23,'François Cluzet','acteur'),(23,'Omar Sy','acteur'),(23,'Olivier Nakache','realisateur'),(23,'Éric Toledano','realisateur'),
 (24,'Marion Cotillard','acteur'),(24,'Gérard Depardieu','acteur'),(24,'Olivier Dahan','realisateur'),
 (25,'Jean Dujardin','acteur'),(25,'Bérénice Bejo','acteur'),(25,'Michel Hazanavicius','realisateur'),
 (26,'Audrey Tautou','acteur'),(26,'Mathieu Kassovitz','acteur'),(26,'Jean-Pierre Jeunet','realisateur'),
 (27,'Vincent Cassel','acteur'),(27,'Hubert Koundé','acteur'),(27,'Saïd Taghmaoui','acteur'),(27,'Mathieu Kassovitz','realisateur'),
 (28,'Michael J. Fox','acteur'),(28,'Christopher Lloyd','acteur'),(28,'Lea Thompson','acteur'),(28,'Robert Zemeckis','realisateur'),
 (29,'Michael J. Fox','acteur'),(29,'Christopher Lloyd','acteur'),(29,'Lea Thompson','acteur'),(29,'Robert Zemeckis','realisateur'),
 (30,'Michael J. Fox','acteur'),(30,'Christopher Lloyd','acteur'),(30,'Lea Thompson','acteur'),(30,'Robert Zemeckis','realisateur');

INSERT INTO personnes (nom) SELECT DISTINCT nom FROM _casting ORDER BY nom;
INSERT INTO casting (film_id, personne_id, role)
SELECT c.film_id, p.id, c.role FROM _casting c JOIN personnes p ON p.nom = c.nom;

-- ---------- Membres (fictifs) ----------
INSERT INTO utilisateurs (pseudo, ville, inscrit_le) VALUES
 ('cinephile_92', 'Nanterre',  '2024-03-12'),
 ('popcorn_queen','Lyon',      '2024-09-01'),
 ('nolanfan',     'Paris',     '2025-01-05'),
 ('maxou_ciné',   'Marseille', '2025-02-20'),
 ('lea.reel',     'Lille',     '2025-04-02'),
 ('darkroom',     'Nantes',    '2025-06-18'),
 ('bobine',       'Bordeaux',  '2025-09-07'),
 ('sofa_critic',  'Paris',     '2025-12-11');

-- ---------- Notes et visionnages (générés, mais déterministes) ----------
-- Chaque film a une « qualité » de base ; chaque membre note autour de cette base.
CREATE TEMP TABLE _base (film_id INTEGER, base NUMERIC);
INSERT INTO _base VALUES
 (1,3.8),(2,4.0),(3,3.6),(4,3.7),(5,3.9),(6,3.0),(7,4.4),(8,3.7),(9,4.3),(10,4.0),
 (11,3.9),(12,4.4),(13,4.2),(14,3.8),(15,4.1),(16,4.4),(17,3.6),(18,4.3),(19,3.9),(20,4.7),
 (21,3.9),(22,4.8),(23,4.3),(24,3.7),(25,3.8),(26,4.2),(27,4.3),(28,4.5),(29,3.9),(30,3.5);

CREATE TEMP TABLE _h AS
SELECT u.id AS utilisateur_id, b.film_id, b.base,
       ('x' || substr(md5(u.id || '-' || b.film_id), 1, 8))::bit(32)::int AS h
FROM utilisateurs u CROSS JOIN _base b;

-- Environ 2 films sur 3 vus par chaque membre
INSERT INTO notes (utilisateur_id, film_id, note, note_le)
SELECT utilisateur_id, film_id,
       LEAST(5, GREATEST(0.5, ROUND((base + ((abs(h) % 11) - 5) * 0.15) * 2) / 2)),
       DATE '2026-01-05' + (abs(h / 7) % 255)
FROM _h
WHERE abs(h) % 3 <> 0;

-- Un visionnage par note, à la date de la note
INSERT INTO journal (utilisateur_id, film_id, date_visionnage)
SELECT utilisateur_id, film_id, note_le FROM notes;

-- Quelques revisionnages
INSERT INTO journal (utilisateur_id, film_id, date_visionnage)
SELECT n.utilisateur_id, n.film_id, n.note_le + 30 + (n.film_id % 20)
FROM notes n
WHERE n.note >= 4.5 AND n.note_le + 30 + (n.film_id % 20) <= DATE '2026-09-20';

DROP TABLE _casting, _base, _h;

-- ---------- Contrôle ----------
SELECT 'films' AS table_name, COUNT(*) AS lignes FROM films
UNION ALL SELECT 'personnes', COUNT(*) FROM personnes
UNION ALL SELECT 'casting', COUNT(*) FROM casting
UNION ALL SELECT 'utilisateurs', COUNT(*) FROM utilisateurs
UNION ALL SELECT 'notes', COUNT(*) FROM notes
UNION ALL SELECT 'journal', COUNT(*) FROM journal;
